### ISSUE TITLE
What's the difference between face and head?

### ISSUE THREAD

**Issue by sylyt62** [hnuzhy/BPJDet#3]
Is the difference concerning face landmarks? 
Do you have any plans to release pretrained weights of body/head or body/head/hand model?

**Comment by hnuzhy** [comment]
No, face landmarks are not considered. BPJDet only focuses on bbox detection. Body-part joint detection including face, head or hand has been released. Body-parts joint detection on dataset COCOHumanParts has not been released. We plan to release corresponding code and pretrained models when our submitted paper has a final decision. Thank you for your concern!

**Comment by sylyt62** [comment]
Congrats!
